### ISSUE TITLE
这个是怎么使用的 有demo吗 只看到你引用了组件。

### ISSUE THREAD

**Issue by zjgk** [yz1311/taro-signature-pad#1]

**Comment by yz1311** [comment]
因为使用很简单，几个方法的话，你直接通过ref的方式调用就行了

**Comment by zjgk** [comment]
好的 谢谢  那手写的这个点击事件是调用的哪个方法 把弹窗面板打开的。

**Comment by yz1311** [comment]
> 好的 谢谢 那手写的这个点击事件是调用的哪个方法 把弹窗面板打开的。

这个只是一个画板view，弹窗的话，你自己用其他组件包裹，譬如taro-ui的AtModal

**Comment by zjgk** [comment]
> > 好的，谢谢那手写的这个点击事件是调用的哪个方法把弹窗面板打开的。
> 
> 只是这个画板视图，弹窗的话，你自己用其他组件包裹，如芋头-ui的AtModal

>好的 ，开始以为调用方法展示的，前几天安装引用组件后没没看到这个手写区域，没看到有可能白色背景重色看所致，等回家我来试试看。
