### ISSUE TITLE
为什么会在源码中报这个错我

### ISSUE THREAD

**Issue by ljxnu** [yz1311/taro-signature-pad#2]
SyntaxError: D:\gitlab\zyx-mini-program\node_modules\@yz1311\taro-signature-pad\lib\signaturePad.tsx: Unexpected reserved word 'interface'. (7:0)

   5 | import './signaturePad.scss';
   6 |
>  7 | interface IProps {
     | ^
   8 |     className?: string;
   9 |     style?: string;
  10 | }

**Comment by yz1311** [comment]
忘了适配非ts项目了，试下  0.0.2-beta1

**Comment by ljxnu** [comment]
你好，请问 0.0.2-beta1在哪，我怎么没有找到

**Comment by yz1311** [comment]
![image](https://user-images.githubusercontent.com/9854019/145512868-754943a7-a6bb-45f4-94dc-8ea8e4ce6682.png)
你切换到npm的源试下
